name: flutter_epic_games_launcher
description: A Flutter GUI to legendary.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  legendary: ^0.1.0
  path: ^1.8.3
  path_provider: ^2.0.15
  provider: ^6.0.5
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
